/** Lightweight catalog metadata safe to import from routing and shell code. */
export const TEMPLATE_SLUGS = [
  "reading-coach",
  "content-lesson",
  "highlight-short",
  "pronunciation-card",
  "chat-bubbles",
  "quote-card",
  "checklist-steps",
  "like-subscribe",
  "hero-title",
  "audiogram",
  "world-globe",
  "bullet-steps",
  "numbered-steps",
  "logo-sting",
  "speaker-card",
  "stat-counter",
  "before-after",
  "bar-chart",
  "line-chart",
  "tweet-card",
  "like-subscribe-bell",
  "blur-focus-text",
  "caption-classic",
  "news-highlight",
  "video-card",
  "b-roll",
  "countdown",
  "ticker-tape",
  "recording-frame",
  "sticker",
  "face-bubble",
  "prompt-box",
  "cortisol-gauge",
  "donut-breakdown",
  "donut-chart",
  "photo-stack",
] as const;

export const TEMPLATE_COUNT = TEMPLATE_SLUGS.length;
