import json,html,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];WORK=ROOT/'work/reading-teacher-elternabend';OUT=ROOT/'renders/reading-teacher-elternabend';lesson=json.loads((WORK/'lesson.json').read_text())
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Elternabend · Guided German reading</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f2e8;color:#173e32;font:17px/1.6 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:45px 30px}h1{font-size:clamp(35px,5vw,62px);line-height:1.13;letter-spacing:-2px}header{font-weight:800;border-bottom:1px solid #cad7c4;padding-bottom:24px}.lead{max-width:850px;font-size:20px;color:#587364}.grid{display:grid;grid-template-columns:1fr;gap:24px;margin-top:35px}article{background:white;border-radius:22px;overflow:hidden;border:1px solid #d5decf}video{width:100%;aspect-ratio:16/9;background:#173e32}.copy{padding:24px}h2{font-size:27px}button,a{color:#176e4e}button{border:1px solid #ccd8c7;background:#eef3e8;padding:10px;border-radius:9px;cursor:pointer;margin:4px}small{color:#587364}.note{margin-top:35px;padding-top:25px;border-top:1px solid #cad7c4}a{display:inline-block;margin:6px 0}@media(max-width:1000px){.grid{grid-template-columns:1fr}main{max-width:850px;padding:24px 18px}}</style><main><header>GetFluentFast ●</header><h1>Feel more at home<br>at your next parents’ evening.</h1><p class="lead">School plans, pick-up times, messages home: let’s make them easier to follow in German. Listen together with short English explanations, then hear the whole meeting again at its usual pace.</p><p><strong>German → English guidance · B2 · Full reading</strong></p><div class="grid">'''
revision=hashlib.sha256((WORK/'lesson.json').read_bytes()).hexdigest()[:12]
scripts=[]
for i,v in enumerate(lesson['variants'],1):
 props=json.loads((WORK/(v['id']+'.props.json')).read_text());p=props['spec']['overlays'][0]['props'];duration=props['spec']['durationSec'];scenes=p['scenes']
 desc={'paper':'First listen at 12% slower speed. Useful German words and phrases are spoken, translated and briefly explained in context, with grammar where needed. Then listen to all 137 sentences again at regular speed without commentary.','cinema':'First hear the whole meeting at 12% slower speed, revisit useful language, then hear the complete reading again at regular speed.','workshop':'A gentler first listen with explanations before three useful practice checks, followed by a complete regular-speed listen.'}[v['treatment']]
 markers=[('abholen + passive',next(s['start'] for s in scenes if s['kind']=='teacher' and s['sentence']==15)),('Hort: word meaning',next(s['start'] for s in scenes if s['kind']=='teacher' and s['sentence']==13)),('Absence note',next(s['start'] for s in scenes if s['kind']=='teacher' and s['sentence']==113)),('Regular-speed second pass',next(s['start'] for s in scenes if s['kind']=='reading' and s.get('pace')=='regular')),('QR closing card',p['readingLink']['endCardStart']+1)]
 page+=f'<article><video id="v{i}" aria-label="{html.escape(v["title"])}" controls playsinline preload="metadata" src="{v["id"]}.mp4?v={revision}" poster="{v["id"]}.png?v={revision}"></video><div class="copy"><small>{int(duration)//60}:{int(duration)%60:02d} · 137 source sentences</small><h2>{html.escape(v["title"])}</h2><p>{desc}</p>'
 for label,time in markers:page+=f'<button data-video="v{i}" data-time="{time}">{label}</button>'
 page+=f'<br><a href="{v["id"]}.mp4" download>Download video</a></div></article>'
 scripts.append('## '+v['title']+'\n\n'+'\n\n'.join(f"Sentence {s['sentence']+1}: {s['text']}" for s in v['scenes'] if s['kind']=='teacher'))
page+='''</div><p class="note">You don’t need to catch every detail at once. On the first listen, we’ll pause briefly for words and structures that help you follow the meeting. On the second, let the whole conversation come together. You can listen through headphones too.</p><p>The QR points to the original Elternabend reading. Public website hosting is still pending; this is a local preview. <a href="http://127.0.0.1:8768/reading/reading_elternabend_seed_de/">Preview the reading landing page</a>.</p><p><a href="script/video-script.md">Complete ordered video script</a> · <a href="script/video-script.json">Structured script</a> · <a href="script/guiding-translation-template.json">Guiding-language translation file</a> · <a href="delivery-qa.json">Media verification</a></p></main><script>const videos=[...document.querySelectorAll('video')];videos.forEach(v=>v.addEventListener('play',()=>videos.forEach(o=>{if(o!==v)o.pause()})));document.querySelectorAll('[data-video]').forEach(b=>b.addEventListener('click',()=>{const v=document.getElementById(b.dataset.video);v.currentTime=Number(b.dataset.time);v.play();v.scrollIntoView({behavior:'smooth',block:'center'});}));</script></html>'''
(OUT/'index.html').write_text(page);(OUT/'teacher-scripts.md').write_text('# Elternabend: German reading, English guidance\n\n'+'\n\n'.join(scripts))
